FROM python:3.10-buster
RUN python3 -m venv venv
COPY requirements.txt .
RUN . venv/bin/activate
RUN apt-get update -y
RUN apt-get install -y gcc
RUN /venv/bin/python -m pip install --upgrade pip
RUN /venv/bin/python -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . /app

WORKDIR /app

EXPOSE 8080
CMD /venv/bin/python probsol_bak.py


